Serilog:
  Using:
    - "Serilog.Sinks.Console"
  MinimumLevel: "Debug"
  WriteTo:
    - Name: "Console"
      Args:
        outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext} {Message}{NewLine}{Exception}"
  Enrich:
    - "FromLogContext"
    - "WithMachineName"
    - "WithThreadId"